# Generated by Django 4.2.16 on 2024-10-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
