# Generated by Django 4.2.16 on 2024-10-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoApp", "0002_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TailorDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("national_id_number", models.CharField(max_length=100, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "passport_size",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/tailor_passports/"
                    ),
                ),
                ("area_of_residence", models.CharField(max_length=255)),
                ("area_of_work", models.CharField(max_length=255)),
                ("date_of_registration", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TailorProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SUIT", "Suit"),
                            ("TSHIRT", "T-Shirt"),
                            ("TROUSER", "Trouser"),
                            ("GAUNI", "Gauni"),
                        ],
                        max_length=10,
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("product_image", models.ImageField(upload_to="media/product_images/")),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("measurement_guides", models.TextField()),
            ],
        ),
    ]
